namespace Base.Api.Enums
{
    public enum CommissionType : byte
    {
        DiscountGroupA,
        DiscountGroupB,
        DiscountGroupC,
        DiscountOther,
        Discount1X2,
        Discount,
        Commission
    }

    public enum EnumReferralRebateType
    {
		Unknown = 0,
		Sbo_Sports = 1,
	    Sbo_Sports_5050_GroupA = 2,
		Sbo_Sports_5050_GroupB = 3,
		Sbo_Sports_5050_GroupC = 4,
		Sbo_Sports_Non5050 = 5,
		Sbo_Sports_1x2 = 6,
		Sbo_Casino = 7,
		Sbo_Games = 8,
		Sbo_VirtualSports = 9,
		Sbo_Lv = 10,
		WM = 11,
		CQNine = 12,
		PragmaticPlay = 13,
        PragmaticPlayCasino = 14,
		DreamGaming = 15,
		BigGaming = 16,
		FlowGaming = 17,
		SexyBaccarat = 18,
		SBO_Game_New= 19, // Celton
		GamingWorld = 20,
		JokerGaming = 21,
		RTG = 22,
		IONLC = 23,
		WorldMatch = 24,
		CreativeGaming = 25,
		Saba = 26,
		FunkyGames = 27,
		IdnLive = 28,
		IdnPoker = 29,
		SaGaming = 30,
		EvolutionGaming = 31,
		SpadeGaming = 32,
		Yggdrasil = 33,
		FunGaming = 34,
		TfGaming = 35,
		PlayTech = 36,
		Habanero = 37,
		AsiaGaming = 38,
		Allbet = 39,
		MicroGaming = 40,
		OrientalGame = 41,
		FiveEightPoker = 42,
		KaiyuanGaming = 43,
		GreenDragon = 44,
		JDB = 45,
		PGSoft = 46,
        FlowGamingHub = 47,
        TwelveLive_RedTiger = 48,
        Gamatron = 49,
		HuaweiFourDigits = 50,
		Saba_Sports = 51,
		Sv388Cockfighting = 52,
		GiocoPlus = 53,
        LionKing = 54,
		RCS = 55,
		LiveCasino568 = 56,
}
}