namespace Base.Api.Enums
{
    public enum EnumGameProvider
    {
		Sbo = -2,
        Unknown = -1,
        Lobby = 10000,
        Wm = 0,
        Lv = 1,
        CQNine = 2,
        PragmaticPlay = 3,
        DreamGaming = 4,
        BigGaming = 5,
        FlowGaming = 6,
        SexyBaccarat = 7,
        SBO_Game_New = 8, // Celton
        GamingWorld = 9,
        JokerGaming = 10,
        RTG = 11,
        RealTimeGaming = 11,
        IONLC = 12,
        WorldMatch = 13,
        CreativeGaming = 14,
        Saba = 15,
        FunkyGames = 16,
        IdnLive = 17,
        IdnPoker = 18,
        SaGaming = 19,
        EvolutionGaming = 20,
        SpadeGaming = 21,
        Yggdrasil = 22,
        FunGaming = 23,
        TfGaming = 24,
        PlayTech = 25,
        Habanero = 26,
        AsiaGaming = 27,
        Allbet = 28,
        MicroGaming = 29,
        OrientalGame = 30,
        FiveEightPoker = 31,
        KaiyuanGaming = 32,
        GreenDragon = 33,
        JDB = 34,
        PGSoft = 35,
        FlowGamingHub = 36,
        PragmaticPlayCasino = 38,
        TwelveLive_RedTiger = 39,
        HuaweiFourDigits = 40,
        Gamatron = 41,
        SabaSeamlessWallet = 44,
        Sv388Cockfighting = 46,
        GiocoPlus = 47,
        RCS = 49,
        LionKing = 50,
        LiveCasino568 = 51,

    }
}