namespace Base.Api.Enums
{
    public enum SboApi
    {
        RegisterAgent = 1,
        RegisterPlayer = 2,
        Login = 3,
        GetBalance = 4,
        Deposit = 5,
        Withdraw = 6,
        Transfer = 7,
		GetSportsBetListByModifyDay = 8,
		GetCasinoBetListByModifyDay = 9,
		GetVirtualSportBetListByModifyDay = 10,
        GetGamesBetListByModifyDay = 11,
        UpdateMemberBetSetting = 12,
        GetSeamlessGameProviderBetListByModifyDate = 13,
        GetLiveVideoByModifyDay = 14,
        UpdateMemberUserGroup = 15,
        GetLeagueIdAndName = 16,
        SetLeagueBetSetting = 17,
        GetLeagueBetSetting = 18,
        SetLeagueGroupBetSetting = 19,
        GetLeagueGroupBetSetting = 20,
        Logout = 21,
        UpdatePlayerStatus = 22,
        UpdateAgentStatus = 23,
        UpdateAgentBetSettings = 24,
        UpdateAgentPresetBetSettingsBySportTypeAndMarketType = 25,
        UpdatePlayerBetSettingsBySportTypeAndMarketType = 26,
        GetLeague = 27,
        GetForecastPage = 28,
        GetLast50Page = 29,
        GetThirdPartyGameList = 30,
        GetCasinoBeautyBetListByModifyDay = 31,
        GetBetDetailReturnUrl = 32,
        GetBetPayload = 33,
        GetSportsBetListByTransId = 34,
        GetCasinoBetListByTransId = 35,
        GetVirtualSportsBetListByTransId = 36,
        GetGamesBetListByTransId = 37,
        GetSeamlessGameProviderBetListByTransId = 38,
        GetSeamlessGameProviderAllBetStatusListByRefno = 39,
        SetPlayerSuspiciousForSports = 40,
        DelaySettleByBets = 41,
        RemoveDelaySettleByBets = 42,
        VoidSingleBetByTransIds = 43,
        GetGameProviderSeamlessSportsBetListByModifydate = 44,
        GetSeamlessGameproviderSportsBetListByRefno =45,
        SetPlayerUnsuspiciousForSports = 46,
        CheckPlayerBehaviorForSports = 47,
        GetBetPayloadReturnUrl = 48,
        GetGameList = 49,
        GetSportsResultPageUrl = 50,
        GetTransferGameProviderBetListByModifyDate = 51,
        GetTransferGameProviderTransferListByModifyDate = 52,
        GetTransferGameProviderTransferListByRefno = 53,
        TransferBetSummaryBySettledTime = 54,
        GetSeamlessGameProviderSportsBetSettings = 55,
        UpdateSeamlessGameProviderSportsBetSettings = 56,
        UpdateAgentPresetSeamlessGameProviderBetSettingsBySportType = 57,
    }
}